### ISSUE TITLE
Are you sure it's correct?

### ISSUE THREAD

**Issue by vedgar** [tammet/logictools#1]
I have a file with a clause -1 -2, but it happily assigns 1 2 3 4 ... as the satisfying assignment. The file is at https://drive.google.com/file/d/0B7lWKZO8hXUGMFlFMlQtUXFIbTA/view?usp=sharing

**Comment by vedgar** [comment]
This is a scam, right? You haven't fixed anything - after 3.5 years, the same bug is still there. What a joke.

**Comment by tammet** [comment]
Indeed, no maintenance so far. Fixing and upgrading right now: a major upgrade of the site is on the way. Thank you for noticing that the error you pointed out is still not ok: looking into that before the upgrade.

**Comment by vedgar** [comment]
Sorry for being rude above, I just assumed you don't care at all. Take your time, I know SAT is hard. :-)

**Comment by tammet** [comment]
Thanks again! Seems to be fixed now: the preprocessor botched the handling of pure literals, i.e. sat/unsat was detected ok, but the valuations of pure literals were wrong. Btw, the major upgrade to http://logictools.org is up and running: there is now a predicate logic solver running on Wasm. The propositional part is as was, except for the fixes.

**Comment by vedgar** [comment]
Thank you very much!
